name: CI/CD

on:
  push:
    branches:
      - master
      - main
    paths:
      - src/**
      - package.json
  pull_request:
    branches:
      - master
      - main
    paths:
      - src/**
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm i
      - run: npm run build
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
